### GET 상세조회
GET http://localhost:8080/v1/api/products/5
Content-Type: application/json
Accept: application/json


### GET 목록조회
GET http://localhost:8080/v1/api/products
Content-Type: application/json
Accept: application/json


###상품 이름 검색
GET http://localhost:8080/v1/api/products?search=yama
Content-Type: application/json
Accept: */*


### 페이지 없는 상품 목록 조
GET http://localhost:8080/v1/api/products/all
Content-Type: application/json
Accept: application/json